### ISSUE TITLE
chefspec wrong number of arguments (1 for 0) compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:39:in `initialize'

### ISSUE THREAD

**Issue by joelhandwell** [haapp/w_memcached#8]
memcached cookbook from version 2.0.0 https://github.com/chef-cookbooks/memcached/tree/v2.0.0 introduced usage of chef_compat cookbook https://github.com/chef-cookbooks/compat_resource and caused following chefspec failure:

```
C:\Users\Joel\Code\ha\memcached>rspec
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
Run options: exclude {:skip=>true}
[2015-12-30T06:50:25+09:00] WARN: Cloning resource attributes for service[memcached] from prior resource (CHEF-3694)
[2015-12-30T06:50:25+09:00] WARN: Previous service[memcached]: C:\Users\Joel\AppData\Local\Temp\d20151230-144876-scx3fh\cookbooks\memcached\recipes\package.rb:69:in `from_file'
[2015-12-30T06:50:25+09:00] WARN: Current  service[memcached]: C:\Users\Joel\AppData\Local\Temp\d20151230-144876-scx3fh\cookbooks\memcached\recipes\configure.rb:74:in `from_file'
.
================================================================================
Recipe Compile Error in C:\Users\Joel\AppData\Local\Temp\d20151230-144876-scx3fh\cookbooks\w_memcached\recipes\default.rb
================================================================================

ArgumentError
-------------
wrong number of arguments (1 for 0)


Cookbook Trace:
---------------
  C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:39:in `initialize'
  C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:39:in `initialize'
  C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:100:in `new'
  C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:100:in `build_resource'
  C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:67:in `declare_resource'

Relevant File Content:
----------------------
C:/Users/Joel/AppData/Local/Temp/d20151230-144876-scx3fh/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:

 32:      attr_reader :cookbook_name
 33:      attr_reader :recipe_name
 34:      attr_reader :enclosing_provider
 35:      attr_reader :resource
 36:
 37:      # FIXME (ruby-2.1 syntax): most of these are mandatory
 38:      def initialize(type:nil, name:nil, created_at: nil, params: nil, run_context: nil, cookbook_name: nil, recipe_name: nil, enclosing_provider: nil)
 39>> super if defined?(::Chef::ResourceBuilder)
 40:        @type               = type
 41:        @name               = name
 42:        @created_at         = created_at
 43:        @params             = params
 44:        @run_context        = run_context
 45:        @cookbook_name      = cookbook_name
 46:        @recipe_name        = recipe_name
 47:        @enclosing_provider = enclosing_provider
 48:      end

F
```

Example build log can be found here https://travis-ci.org/haapp/w_memcached/jobs/99243231

Until this failure solves, we'll downgrade and use memcached cookbook version 1.9.0

**Comment by joelhandwell** [comment]
Fixed as we update memcached cookbook to 3.x
